# Generated by Django 4.2.6 on 2023-10-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reserva', '0003_reserva_cantidad_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Fecha_vencida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de la reserva'),
        ),
    ]
