# Generated by Django 4.2.6 on 2023-10-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudiante', '0001_initial'),
        ('Ejemplar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad_dias', models.SmallIntegerField(default=10, verbose_name='Cantidad de Dias a Reservar')),
                ('Fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('Fecha_vencida', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento de la reserva')),
                ('Estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('Ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ejemplar.ejemplar')),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudiante.estudiante')),
            ],
            options={
                'verbose_name': 'prestamo',
                'verbose_name_plural': 'prestamos',
            },
        ),
    ]
